%timeit 多次运行取运行时间的平均值

# Numpy为何如此高效
* 用C语言实现
* 数据类型是统一的，执行更加高效
* python有线程锁，无法实现真正的多线程并行，c可以
* 需要利用到python for 或者一些矩阵化，向量化的操作后

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [2]:
import numpy as np
x = np.array([1,2,3,4,5] ,dtype = float)
print(x)

[1. 2. 3. 4. 5.]


In [3]:
x = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]
             ])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [4]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [5]:
np.ones((2,4),dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.full((3,5),8.8)

array([[8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [10]:
np.linspace(0,1,4) #0到1之间4个数

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [11]:
np.logspace(1,10,10,base=2) #等比数列 参数是幂 base 是进制

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [12]:
np.random.random((3,3))

array([[0.20298315, 0.50314365, 0.0369147 ],
       [0.88439862, 0.71708656, 0.98940421],
       [0.93614381, 0.80416243, 0.2656641 ]])

In [13]:
np.random.normal(0,1,(3,3))

array([[ 0.15523817,  0.92799162,  0.7718426 ],
       [-0.58380025,  0.44658023,  1.13228744],
       [ 1.14266021, -0.55543075,  1.17436911]])

In [14]:
np.random.randint(0,10,(3,3))

array([[0, 0, 8],
       [1, 1, 1],
       [6, 9, 2]])

In [15]:
x = np.array([10,20,30,40])
np.random.permutation(x) # 不改变原数组

array([40, 10, 30, 20])

In [16]:
np.random.shuffle(x)

In [17]:
np.random.choice(x,size = (4,3))

array([[20, 30, 30],
       [10, 10, 40],
       [40, 20, 30],
       [30, 10, 10]])

## 数组索引

In [18]:
x2 = np.random.randint(0,20,(2,3))

In [19]:
x2[0,0]
x2[1][2]

10

In [20]:
x2[0][0] = 0.619

In [21]:
x2

array([[ 0,  7, 14],
       [ 0,  1, 10]])

## 数组切片

In [22]:
x = np.arange(10)

In [23]:
x[:3] # 左闭右开

array([0, 1, 2])

In [24]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x2 = np.random.randint(20,size=(3,4))
x2[:2][:3]

array([[14,  4, 13,  5],
       [11,  0, 12, 13]])

In [27]:
x2

array([[14,  4, 13,  5],
       [11,  0, 12, 13],
       [13, 16,  7,  7]])

In [28]:
x2[:2][:3]

array([[14,  4, 13,  5],
       [11,  0, 12, 13]])

In [29]:
x2[:2,:3]

array([[14,  4, 13],
       [11,  0, 12]])

In [30]:
x2[:2,0:3:2]

array([[14, 13],
       [11, 12]])

In [31]:
x3 = np.random.randint(20,size=(3,4))

In [32]:
x3 [1,:] # 取得行

array([ 6, 13, 19, 14])

In [33]:
x3[1]

array([ 6, 13, 19, 14])

In [34]:
x3[1,:]

array([ 6, 13, 19, 14])

In [35]:
x3[:,1] # 列

array([ 3, 13, 19])

In [36]:
x3

array([[11,  3, 17,  8],
       [ 6, 13, 19, 14],
       [ 8, 19,  0, 10]])

> 切片不是副本 只是一个视图！！！ 对切片的修改会影响到原来数组

In [37]:
x4 = x3 [:2,:3] 

In [38]:
x4

array([[11,  3, 17],
       [ 6, 13, 19]])

In [39]:
x4[0,0] = 0
x4

array([[ 0,  3, 17],
       [ 6, 13, 19]])

In [40]:
x3

array([[ 0,  3, 17,  8],
       [ 6, 13, 19, 14],
       [ 8, 19,  0, 10]])

In [41]:
x6 = x3[:2,:3].copy()
x6

array([[ 0,  3, 17],
       [ 6, 13, 19]])

In [42]:
x5 = np.random.randint(0,10,(12,))

In [43]:
x5.shape

(12,)

In [44]:
x6 = x5.reshape(3,4)

In [45]:
x6

array([[4, 4, 5, 2],
       [3, 3, 0, 5],
       [8, 3, 3, 4]])

> reshape返回的耶不是副本 只是一个视图！！！ 对切片的修改会影响到原来数组

In [46]:
x7 = x5.reshape(1,x5.shape[0])

In [47]:
x7.shape

(1, 12)

In [48]:
x8 = x5.reshape(x5.shape[0],1)
x8

array([[4],
       [4],
       [5],
       [2],
       [3],
       [3],
       [0],
       [5],
       [8],
       [3],
       [3],
       [4]])

In [49]:
x9 = x5[np.newaxis,:]

In [50]:
x9

array([[4, 4, 5, 2, 3, 3, 0, 5, 8, 3, 3, 4]])

In [51]:
x10 = np.random.randint(0,10,(3,4))
x11 = x10.flatten()

In [52]:
x11

array([9, 9, 3, 1, 1, 8, 7, 0, 1, 4, 9, 0])

> 注意返回的是副本

In [53]:
x11 = x10.ravel() # 视图
x11

array([9, 9, 3, 1, 1, 8, 7, 0, 1, 4, 9, 0])

In [54]:
x12 = x10.reshape(-1) # 视图
x12

array([9, 9, 3, 1, 1, 8, 7, 0, 1, 4, 9, 0])

## numpy 数组拼接

1. 水平拼接

In [55]:
x1 = np.array([[1,2,3],
              [4,5,6]])
x2 = np.array([[7,8,9],
              [0,1,2]])
x3 = np.hstack([x1,x2]) # 非视图

In [56]:
x3

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

In [57]:
x3.shape

(2, 6)

In [58]:
x3[0,0] = 0

In [59]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
x4 = np.c_[x1,x2]
x4

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

2. 垂直拼接

In [61]:
x1 = np.array([[1,2,3],
              [4,5,6]])
x2 = np.array([[7,8,9],
              [0,1,2]])
x5 = np.vstack([x1,x2]) # 非视图
x6 = np.r_[x1,x2]

In [62]:
x6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

3. 数组分裂

In [63]:
x6 = np.arange(10) 
x1,x2,x3 = np.split(x6,[2,7]) # split方法
x1,x2,x3

(array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9]))

In [64]:
x7 = np.arange(1,26).reshape(5,5)
x7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
right ,middle,left = np.hsplit(x7,[2,4]) #水平分割

In [66]:
right,middle,left

(array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]]), array([[ 5],
        [10],
        [15],
        [20],
        [25]]))

In [67]:
up,middle,down = np.vsplit(x7,[2,4])

In [68]:
up,middle,down

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25]]))

## 向量运算 (向量化）

1. 加减乘除
2. 三角函数 np.cos sin log log2 log10 exp

数组运算
1. 按位置计算

矩阵转置，乘法 T dot

## 广播
如果两个数组的形状在维度上不匹配  
那么数组的形式会沿着维度为1的温蒂进行扩展以匹配另一个数组的形状

In [69]:
x1 = np.ones((3,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
x2 = np.arange(3).reshape(1,3)

In [71]:
x2

array([[0, 1, 2]])

In [72]:
x1 + x2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [73]:
x3 = np.logspace(1,10,10,base=2).reshape(2,5) # base 是进制 参数是幂

In [74]:
x4 = np.array([1, 2, 4, 8, 16])

In [75]:
x3 / x4

array([[ 2.,  2.,  2.,  2.,  2.],
       [64., 64., 64., 64., 64.]])

In [76]:
np.ones((3,1))+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 比较运算和掩码 

In [77]:
x1 = np.random.randint(100,size = (10,10))
x1

array([[55, 24, 37, 53, 54, 29, 93, 13, 18, 55],
       [58, 50, 24, 95, 52,  4, 98, 56, 56, 44],
       [32,  1, 75, 57, 83, 67, 36, 64, 97, 17],
       [37, 13, 36, 65, 66,  0, 22, 82, 63, 33],
       [95, 62, 77, 26, 87, 17, 38, 98, 20, 54],
       [72, 26, 41, 34,  7,  1,  5, 21, 39,  7],
       [88, 93, 23, 26, 78, 14, 62,  5, 70,  4],
       [40,  7, 40, 21, 99, 56,  4, 35, 24, 28],
       [76, 51, 82, 21,  6, 34, 71, 31, 85, 44],
       [61, 80, 18, 88, 12,  5, 60, 37, 16, 58]])

In [78]:
x1 * (x1 > 50)

array([[55,  0,  0, 53, 54,  0, 93,  0,  0, 55],
       [58,  0,  0, 95, 52,  0, 98, 56, 56,  0],
       [ 0,  0, 75, 57, 83, 67,  0, 64, 97,  0],
       [ 0,  0,  0, 65, 66,  0,  0, 82, 63,  0],
       [95, 62, 77,  0, 87,  0,  0, 98,  0, 54],
       [72,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [88, 93,  0,  0, 78,  0, 62,  0, 70,  0],
       [ 0,  0,  0,  0, 99, 56,  0,  0,  0,  0],
       [76, 51, 82,  0,  0,  0, 71,  0, 85,  0],
       [61, 80,  0, 88,  0,  0, 60,  0,  0, 58]])

In [79]:
np.sum(x1 > 5)

91

In [80]:
np.all(x1 > 0)

False

In [81]:
np.any(x2 == 6)

False

In [82]:
np.all(x1 < 8,axis = 1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [83]:
(x1 < 9) &(x1 > 5)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [84]:
x3 = np.random.randint(10,size=(3,4))

In [85]:
np.all(x3>3,axis = 0)

array([False, False, False,  True])

In [86]:
x3

array([[4, 1, 0, 5],
       [1, 5, 6, 5],
       [7, 7, 4, 7]])

In [87]:
x1[x1 > 5]

array([55, 24, 37, 53, 54, 29, 93, 13, 18, 55, 58, 50, 24, 95, 52, 98, 56,
       56, 44, 32, 75, 57, 83, 67, 36, 64, 97, 17, 37, 13, 36, 65, 66, 22,
       82, 63, 33, 95, 62, 77, 26, 87, 17, 38, 98, 20, 54, 72, 26, 41, 34,
        7, 21, 39,  7, 88, 93, 23, 26, 78, 14, 62, 70, 40,  7, 40, 21, 99,
       56, 35, 24, 28, 76, 51, 82, 21,  6, 34, 71, 31, 85, 44, 61, 80, 18,
       88, 12, 60, 37, 16, 58])

### 花哨索引

In [88]:
x = np.random.randint(100,size = 10)
ind = [2, 6, 9]

In [89]:
x[ind]

array([54, 60,  4])

In [90]:
ind = np.array([[1, 0],
              [2, 3]])
x[ind]

array([[53, 64],
       [54, 35]])

### 多维数组

In [91]:
x = np.arange(12).reshape(3,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
row = np.array([0, 1, 2])
col = np.array([1, 3, 0])
x[row, col]

array([1, 7, 8])

In [93]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [94]:
x[row[:,np.newaxis],col] # 广播机制

array([[ 1,  3,  0],
       [ 5,  7,  4],
       [ 9, 11,  8]])

* 一些骚操作


In [95]:
x = np.random.randint(20, 50, size = 10)
x

array([33, 34, 21, 22, 43, 25, 28, 48, 44, 44])

In [96]:
i = np.argsort(x)
i

array([2, 3, 5, 6, 0, 1, 4, 8, 9, 7])

In [97]:
i.dtype

dtype('int64')

In [98]:
print("max",np.max(x))
print("min",np.min(x))

max 48
min 21


In [99]:
print("max_index",np.argmax(x))
print("min_index",np.argmin(x))

max_index 7
min_index 2


In [100]:
x = np.arange(6).reshape(2,3)
print(x)
print(np.sum(x))
print(np.sum(x,axis = 1))
print(np.sum(x,axis = 0))

[[0 1 2]
 [3 4 5]]
15
[ 3 12]
[3 5 7]


> 标准差 方差 中位数 均值均可返回