%timeit 多次运行取运行时间的平均值

# Numpy为何如此高效
* 用C语言实现
* 数据类型是统一的，执行更加高效
* python有线程锁，无法实现真正的多线程并行，c可以
* 需要利用到python for 或者一些矩阵化，向量化的操作后

In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [9]:
import numpy as np
x = np.array([1,2,3,4,5] ,dtype = float)
print(x)

[1. 2. 3. 4. 5.]


In [10]:
x = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]
             ])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [11]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones((2,4),dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.full((3,5),8.8)

array([[8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [19]:
np.linspace(0,1,4) #0到1之间4个数

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [129]:
np.logspace(1,10,10,base=2) #等比数列 参数是幂 base 是进制

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [23]:
np.random.random((3,3))

array([[0.83662018, 0.68900745, 0.20289083],
       [0.57880104, 0.55044952, 0.32837961],
       [0.26265417, 0.46075913, 0.90793483]])

In [24]:
np.random.normal(0,1,(3,3))

array([[ 1.02969109, -0.05187673, -0.35773322],
       [ 0.84438653, -0.58776631, -0.03212037],
       [-2.05448644,  0.59920639, -1.1734043 ]])

In [25]:
np.random.randint(0,10,(3,3))

array([[6, 6, 0],
       [7, 3, 6],
       [3, 5, 8]])

In [26]:
x = np.array([10,20,30,40])
np.random.permutation(x) # 不改变原数组

array([30, 20, 40, 10])

In [27]:
np.random.shuffle(x)

In [28]:
np.random.choice(x,size = (4,3))

array([[20, 10, 10],
       [40, 10, 40],
       [10, 10, 20],
       [30, 30, 40]])

## 数组索引

In [29]:
x2 = np.random.randint(0,20,(2,3))

In [30]:
x2[0,0]
x2[1][2]

0

In [31]:
x2[0][0] = 0.619

In [32]:
x2

array([[0, 1, 9],
       [9, 6, 0]])

## 数组切片

In [34]:
x = np.arange(10)

In [35]:
x[:3]

array([0, 1, 2])

In [37]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [38]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
x2 = np.random.randint(20,size=(3,4))
x2[:2][:3]

array([[ 1,  6, 17,  2],
       [14,  7,  0,  0]])

In [40]:
x2

array([[ 1,  6, 17,  2],
       [14,  7,  0,  0],
       [11, 17, 15,  9]])

In [42]:
x2[:2][:3]

array([[ 1,  6, 17,  2],
       [14,  7,  0,  0]])

In [43]:
x2[:2,:3]

array([[ 1,  6, 17],
       [14,  7,  0]])

In [45]:
x2[:2,0:3:2]

array([[ 1, 17],
       [14,  0]])

In [46]:
x3 = np.random.randint(20,size=(3,4))

In [47]:
x3 [1,:] # 取得行

array([ 9, 16,  1,  5])

In [48]:
x3[1]

array([ 9, 16,  1,  5])

In [49]:
x3[1,:]

array([ 9, 16,  1,  5])

In [50]:
x3[:,1] # 列

array([ 2, 16, 18])

In [51]:
x3

array([[10,  2, 18, 15],
       [ 9, 16,  1,  5],
       [ 8, 18, 17, 18]])

> 切片不是副本 只是一个视图！！！ 对切片的修改会影响到原来数组

In [52]:
x4 = x3 [:2,:3] 

In [53]:
x4

array([[10,  2, 18],
       [ 9, 16,  1]])

In [54]:
x4[0,0] = 0
x4

array([[ 0,  2, 18],
       [ 9, 16,  1]])

In [56]:
x3

array([[ 0,  2, 18, 15],
       [ 9, 16,  1,  5],
       [ 8, 18, 17, 18]])

In [57]:
x6 = x3[:2,:3].copy()
x6

array([[ 0,  2, 18],
       [ 9, 16,  1]])

In [58]:
x5 = np.random.randint(0,10,(12,))

In [61]:
x5.shape

(12,)

In [62]:
x6 = x5.reshape(3,4)

In [63]:
x6

array([[3, 4, 9, 7],
       [9, 2, 1, 6],
       [5, 1, 4, 3]])

> reshape返回的耶不是副本 只是一个视图！！！ 对切片的修改会影响到原来数组

In [66]:
x7 = x5.reshape(1,x5.shape[0])

In [67]:
x7.shape

(1, 12)

In [68]:
x8 = x5.reshape(x5.shape[0],1)
x8

array([[3],
       [4],
       [9],
       [7],
       [9],
       [2],
       [1],
       [6],
       [5],
       [1],
       [4],
       [3]])

In [71]:
x9 = x5[np.newaxis,:]

In [72]:
x9

array([[3, 4, 9, 7, 9, 2, 1, 6, 5, 1, 4, 3]])

In [73]:
x10 = np.random.randint(0,10,(3,4))
x11 = x10.flatten()

In [74]:
x11

array([6, 7, 5, 3, 5, 1, 2, 8, 8, 1, 8, 0])

> 注意返回的是副本

In [77]:
x11 = x10.ravel() # 视图
x11

array([6, 7, 5, 3, 5, 1, 2, 8, 8, 1, 8, 0])

In [79]:
x12 = x10.reshape(-1) # 视图
x12

array([6, 7, 5, 3, 5, 1, 2, 8, 8, 1, 8, 0])

## numpy 数组拼接

1. 水平拼接

In [88]:
x1 = np.array([[1,2,3],
              [4,5,6]])
x2 = np.array([[7,8,9],
              [0,1,2]])
x3 = np.hstack([x1,x2]) # 非视图

In [86]:
x3

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

In [87]:
x3.shape

(2, 6)

In [89]:
x3[0,0] = 0

In [90]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
x4 = np.c_[x1,x2]
x4

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

2. 垂直拼接

In [93]:
x1 = np.array([[1,2,3],
              [4,5,6]])
x2 = np.array([[7,8,9],
              [0,1,2]])
x5 = np.vstack([x1,x2]) # 非视图
x6 = np.r_[x1,x2]

In [94]:
x6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

3. 数组分裂

In [97]:
x6 = np.arange(10) 
x1,x2,x3 = np.split(x6,[2,7]) # split方法
x1,x2,x3

(array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9]))

In [100]:
x7 = np.arange(1,26).reshape(5,5)
x7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
right ,middle,left = np.hsplit(x7,[2,4]) #水平分割

In [102]:
right,middle,left

(array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]), array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]]), array([[ 5],
        [10],
        [15],
        [20],
        [25]]))

In [105]:
up,middle,down = np.vsplit(x7,[2,4])

In [106]:
up,middle,down

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25]]))

## 向量运算 (向量化）

1. 加减乘除
2. 三角函数 np.cos sin log log2 log10 exp

数组运算
1. 按位置计算

矩阵转置，乘法 T dot

## 广播
如果两个数组的形状在维度上不匹配  
那么数组的形式会沿着维度为1的温蒂进行扩展以匹配另一个数组的形状

In [109]:
x1 = np.ones((3,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
x2 = np.arange(3).reshape(1,3)

In [111]:
x2

array([[0, 1, 2]])

In [112]:
x1 + x2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [130]:
x3 = np.logspace(1,10,10,base=2).reshape(2,5) # base 是进制 参数是幂

In [131]:
x4 = np.array([1, 2, 4, 8, 16])

In [132]:
x3 / x4

array([[ 2.,  2.,  2.,  2.,  2.],
       [64., 64., 64., 64., 64.]])

In [133]:
np.ones((3,1))+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 比较运算和掩码 

In [134]:
x1 = np.random.randint(100,size = (10,10))
x1

array([[78, 35, 57, 32, 69, 32, 63, 89, 19, 79],
       [59, 61, 25, 77,  1,  2, 62, 25, 52,  5],
       [82, 13, 42, 31, 99,  1, 31, 50, 52, 73],
       [ 7, 60, 80, 44, 97,  5, 59, 29, 96,  7],
       [65, 29, 75, 31, 70, 89, 90, 19, 78, 54],
       [32,  4, 12, 38, 55, 55, 95, 41, 52, 67],
       [30, 52, 65, 20, 83,  0, 91, 14, 92, 74],
       [90, 40, 84, 13, 88, 26, 92, 88, 32, 39],
       [36, 95, 99, 11, 46, 44, 22, 28,  9, 83],
       [65, 32, 62, 73, 61, 31, 81, 43, 96, 38]])

In [136]:
x1 * (x1 > 50)

array([[78,  0, 57,  0, 69,  0, 63, 89,  0, 79],
       [59, 61,  0, 77,  0,  0, 62,  0, 52,  0],
       [82,  0,  0,  0, 99,  0,  0,  0, 52, 73],
       [ 0, 60, 80,  0, 97,  0, 59,  0, 96,  0],
       [65,  0, 75,  0, 70, 89, 90,  0, 78, 54],
       [ 0,  0,  0,  0, 55, 55, 95,  0, 52, 67],
       [ 0, 52, 65,  0, 83,  0, 91,  0, 92, 74],
       [90,  0, 84,  0, 88,  0, 92, 88,  0,  0],
       [ 0, 95, 99,  0,  0,  0,  0,  0,  0, 83],
       [65,  0, 62, 73, 61,  0, 81,  0, 96,  0]])

In [138]:
np.sum(x1 > 5)

93

In [139]:
np.all(x1 > 0)

False

In [141]:
np.any(x2 == 6)

False

In [146]:
np.all(x1 < 8,axis = 1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [148]:
(x1 < 9) &(x1 > 5)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [151]:
x3 = np.random.randint(10,size=(3,4))

In [155]:
np.all(x3>3,axis = 0)

array([ True, False, False, False])

In [154]:
x3

array([[5, 6, 0, 5],
       [5, 3, 4, 3],
       [4, 0, 5, 5]])

In [157]:
x1[x1 > 5]

array([78, 35, 57, 32, 69, 32, 63, 89, 19, 79, 59, 61, 25, 77, 62, 25, 52,
       82, 13, 42, 31, 99, 31, 50, 52, 73,  7, 60, 80, 44, 97, 59, 29, 96,
        7, 65, 29, 75, 31, 70, 89, 90, 19, 78, 54, 32, 12, 38, 55, 55, 95,
       41, 52, 67, 30, 52, 65, 20, 83, 91, 14, 92, 74, 90, 40, 84, 13, 88,
       26, 92, 88, 32, 39, 36, 95, 99, 11, 46, 44, 22, 28,  9, 83, 65, 32,
       62, 73, 61, 31, 81, 43, 96, 38])

### 花哨索引

In [158]:
x = np.random.randint(100,size = 10)
ind = [2, 6, 9]

In [159]:
x[ind]

array([38, 41, 26])

In [161]:
ind = np.array([[1, 0],
              [2, 3]])
x[ind]

array([[49,  5],
       [38, 78]])

### 多维数组

In [163]:
x = np.arange(12).reshape(3,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
row = np.array([0, 1, 2])
col = np.array([1, 3, 0])
x[row, col]

array([1, 7, 8])

In [165]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [167]:
x[row[:,np.newaxis],col] # 广播机制

array([[ 1,  3,  0],
       [ 5,  7,  4],
       [ 9, 11,  8]])

* 一些骚操作


In [171]:
x = np.random.randint(20, 50, size = 10)
x

array([45, 42, 46, 29, 48, 32, 47, 28, 47, 32])

In [173]:
i = np.argsort(x)
i

array([7, 3, 5, 9, 1, 0, 2, 6, 8, 4])

In [175]:
i.dtype

dtype('int64')

In [176]:
print("max",np.max(x))
print("min",np.min(x))

max 48
min 28


In [178]:
print("max_index",np.argmax(x))
print("min_index",np.argmin(x))

max_index 4
min_index 7


In [184]:
x = np.arange(6).reshape(2,3)
print(x)
print(np.sum(x))
print(np.sum(x,axis = 1))
print(np.sum(x,axis = 0))

[[0 1 2]
 [3 4 5]]
15
[ 3 12]
[3 5 7]


> 标准差 方差 中位数 均值均可返回