In [2]:
import numpy as np

In [22]:
a = np.random.random(size = [4,6])

In [4]:
print(a.shape)
print(a.dtype)
print(a.nbytes)

(4, 6)
float64
192


In [24]:
a = a.reshape(3,8)

In [25]:
a.shape

(3, 8)

In [26]:
b = a.flatten()

In [27]:
b

array([0.10143209, 0.06827016, 0.55537755, 0.2992069 , 0.84301593,
       0.66981533, 0.79115691, 0.59444644, 0.06156563, 0.98192859,
       0.91198486, 0.58790311, 0.27311843, 0.59996486, 0.28384237,
       0.74393409, 0.75794843, 0.62956808, 0.49902673, 0.41132839,
       0.38094362, 0.64008074, 0.48508274, 0.12378137])

In [3]:
x1 = np.random.random((4,4))
x2 = np.random.random((4,4))
x3 = np.vstack([x1,x2]) # 垂直拼接
x4 = np.hstack([x1,x2]) # 水平拼接

In [4]:
print(x3)
print(x4)

[[0.51936956 0.14973894 0.48239218 0.15694447]
 [0.46032809 0.06705428 0.76003787 0.77022338]
 [0.82594593 0.69671367 0.9543917  0.12137914]
 [0.31788763 0.034569   0.18283762 0.16835587]
 [0.28499447 0.08820526 0.84376645 0.73913585]
 [0.61366308 0.57728209 0.094835   0.16451438]
 [0.55958203 0.1581019  0.58895707 0.0751602 ]
 [0.94772545 0.12704018 0.63376277 0.29707965]]
[[0.51936956 0.14973894 0.48239218 0.15694447 0.28499447 0.08820526
  0.84376645 0.73913585]
 [0.46032809 0.06705428 0.76003787 0.77022338 0.61366308 0.57728209
  0.094835   0.16451438]
 [0.82594593 0.69671367 0.9543917  0.12137914 0.55958203 0.1581019
  0.58895707 0.0751602 ]
 [0.31788763 0.034569   0.18283762 0.16835587 0.94772545 0.12704018
  0.63376277 0.29707965]]


In [9]:
x5 = np.zeros([16,16])
x5[:,0]=1
x5[:,15]=1
x5[0,:]=1
x5[15,:]=1
x5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [16]:
x6 = np.random.uniform(0,100,size = (100,100)) # 一定范围的随机数

In [17]:
print(x6.mean())
print(x6.std())
print(x6.var())

50.29889892315551
28.940358299432997
837.5443384995605


In [23]:
x6 = (x6 - x6.mean())/x6.std()

In [24]:
x6

array([[-1.55878403,  0.10024022,  1.1044261 , ..., -0.38074059,
         0.31804041,  0.81824481],
       [-0.75863935,  0.82771633, -1.2031332 , ..., -0.41927427,
        -1.43425969, -0.26502619],
       [-0.47442745, -1.6701156 , -0.52359242, ..., -1.70461403,
        -0.72270866, -0.92502712],
       ...,
       [ 1.17410586, -0.846141  ,  1.4158436 , ..., -1.20208763,
        -0.19653709, -1.26787407],
       [-0.51347997,  1.59947165,  0.68740881, ..., -0.58202693,
        -0.76579287,  0.47514353],
       [-0.1568056 , -0.06774657, -1.21985301, ...,  0.93380373,
        -1.57281561,  1.17480858]])

In [25]:
print(x6.max())
print(x6.argmax())
print(x6.min())
print(x6.argmin())

1.7173216416642176
884
-1.7378321842570041
3170


In [30]:
x8 = np.random.uniform(80,100,size=(30,))

In [31]:
x8[x8 >= 95]

array([98.12446979, 99.56756368, 97.92575767, 95.76897873])

In [32]:
x8[x8 <= 85]

array([81.04590256, 82.23435434, 82.73898837, 80.32907441, 80.75014114,
       81.08957462, 80.98947737, 81.55697155, 80.79192789, 82.2212795 ,
       84.23189307])

In [35]:
x8[(x8 > 85) & (x8 < 95)] # 记住这个运算符

array([91.04992567, 94.86714952, 94.07639276, 85.51829477, 92.80797832,
       94.52448605, 94.51292238, 92.47305246, 85.13264561, 90.16441   ,
       89.96681553, 85.15883309, 88.10461762, 90.83483065, 85.16916945])

In [36]:
x8.sort() # 改变原数组

In [37]:
x8

array([80.32907441, 80.75014114, 80.79192789, 80.98947737, 81.04590256,
       81.08957462, 81.55697155, 82.2212795 , 82.23435434, 82.73898837,
       84.23189307, 85.13264561, 85.15883309, 85.16916945, 85.51829477,
       88.10461762, 89.96681553, 90.16441   , 90.83483065, 91.04992567,
       92.47305246, 92.80797832, 94.07639276, 94.51292238, 94.52448605,
       94.86714952, 95.76897873, 97.92575767, 98.12446979, 99.56756368])

In [38]:
A = np.random.random(size = (3,3))
B = np.random.random(size = (3,3))

In [47]:
%%time
ABfor = np.zeros([3,3])
for i in range(3):
    for j in range(3):
        result = 0
        for k in range(3):
            result+=A[i][k]*B[k][j]
        ABfor[i][j] = result


CPU times: user 90 µs, sys: 15 µs, total: 105 µs
Wall time: 204 µs


In [44]:
ABfor

array([[1.34252834, 1.21076665, 1.9691596 ],
       [0.68540358, 0.58655415, 0.85613199],
       [1.28747503, 1.11909264, 1.71100067]])

In [48]:
%%time
ABfor1 = np.dot(A,B)

CPU times: user 152 µs, sys: 44 µs, total: 196 µs
Wall time: 148 µs


In [46]:
ABfor1

array([[1.34252834, 1.21076665, 1.9691596 ],
       [0.68540358, 0.58655415, 0.85613199],
       [1.28747503, 1.11909264, 1.71100067]])

In [51]:
%%time
mulABfor = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        mulABfor[i][j] = A[i][j]*B[i][j]
mulABfor

CPU times: user 48 µs, sys: 1 µs, total: 49 µs
Wall time: 51 µs


array([[0.37692743, 0.49342169, 0.5910735 ],
       [0.29374951, 0.01276195, 0.37968615],
       [0.61361552, 0.27258624, 0.59414239]])

In [52]:
%%time
mulAB = A*B
mulAB

CPU times: user 40 µs, sys: 1 µs, total: 41 µs
Wall time: 46.3 µs


array([[0.37692743, 0.49342169, 0.5910735 ],
       [0.29374951, 0.01276195, 0.37968615],
       [0.61361552, 0.27258624, 0.59414239]])